PRAGMA foreign_keys = ON;
CREATE TABLE user (id TEXT PRIMARY KEY, name TEXT NOT NULL, email TEXT NOT NULL UNIQUE, email_verified INTEGER NOT NULL DEFAULT 0, image TEXT, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE TABLE session (id TEXT PRIMARY KEY, expires_at INTEGER NOT NULL, token TEXT NOT NULL UNIQUE, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, ip_address TEXT, user_agent TEXT, user_id TEXT NOT NULL REFERENCES user(id) ON DELETE CASCADE);
CREATE INDEX session_user ON session(user_id);
CREATE TABLE account (id TEXT PRIMARY KEY, account_id TEXT NOT NULL, provider_id TEXT NOT NULL, user_id TEXT NOT NULL REFERENCES user(id) ON DELETE CASCADE, access_token TEXT, refresh_token TEXT, id_token TEXT, access_token_expires_at INTEGER, refresh_token_expires_at INTEGER, scope TEXT, password TEXT, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE INDEX account_user ON account(user_id);
CREATE TABLE verification (id TEXT PRIMARY KEY, identifier TEXT NOT NULL, value TEXT NOT NULL, expires_at INTEGER NOT NULL, created_at INTEGER, updated_at INTEGER);
CREATE INDEX verification_identifier ON verification(identifier);
CREATE TABLE rate_limit (id TEXT PRIMARY KEY, key TEXT NOT NULL UNIQUE, count INTEGER NOT NULL, last_request INTEGER NOT NULL);
CREATE TABLE admins (user_id TEXT PRIMARY KEY REFERENCES user(id) ON DELETE CASCADE);
CREATE TABLE courses (id TEXT PRIMARY KEY, slug TEXT NOT NULL UNIQUE, title TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', image_url TEXT, instructor TEXT NOT NULL DEFAULT '', level TEXT NOT NULL DEFAULT 'Beginner', published INTEGER NOT NULL DEFAULT 0 CHECK(published IN (0,1)), sort_order INTEGER NOT NULL DEFAULT 0);
CREATE TABLE sections (id TEXT PRIMARY KEY, course_id TEXT NOT NULL REFERENCES courses(id) ON DELETE CASCADE, title TEXT NOT NULL, sort_order INTEGER NOT NULL DEFAULT 0);
CREATE INDEX sections_course ON sections(course_id,sort_order);
CREATE TABLE lessons (id TEXT PRIMARY KEY, section_id TEXT NOT NULL REFERENCES sections(id) ON DELETE CASCADE, title TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', video_url TEXT, content TEXT NOT NULL DEFAULT '', duration_seconds INTEGER NOT NULL DEFAULT 0 CHECK(duration_seconds >= 0), preview INTEGER NOT NULL DEFAULT 0 CHECK(preview IN (0,1)), published INTEGER NOT NULL DEFAULT 0 CHECK(published IN (0,1)), sort_order INTEGER NOT NULL DEFAULT 0);
CREATE INDEX lessons_section ON lessons(section_id,sort_order);
CREATE TABLE products (id TEXT PRIMARY KEY, title TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', price_cents INTEGER NOT NULL CHECK(price_cents > 0), currency TEXT NOT NULL DEFAULT 'MYR' CHECK(currency = 'MYR'), active INTEGER NOT NULL DEFAULT 0 CHECK(active IN (0,1)));
CREATE TABLE product_courses (product_id TEXT NOT NULL REFERENCES products(id) ON DELETE CASCADE, course_id TEXT NOT NULL REFERENCES courses(id), PRIMARY KEY(product_id,course_id));
CREATE TABLE orders (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES user(id), product_id TEXT NOT NULL REFERENCES products(id), product_title TEXT NOT NULL, amount_cents INTEGER NOT NULL CHECK(amount_cents > 0), currency TEXT NOT NULL DEFAULT 'MYR', status TEXT NOT NULL CHECK(status IN ('creating','pending','paid','failed')), bill_id TEXT UNIQUE, payment_url TEXT, created_at INTEGER NOT NULL, paid_at INTEGER, collection_id TEXT NOT NULL);
CREATE INDEX orders_user ON orders(user_id,created_at);
CREATE UNIQUE INDEX orders_pending ON orders(user_id,product_id) WHERE status IN ('creating','pending');
CREATE TABLE order_courses (order_id TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE, course_id TEXT NOT NULL REFERENCES courses(id), PRIMARY KEY(order_id,course_id));
CREATE TABLE payment_attempts (id TEXT PRIMARY KEY, order_id TEXT NOT NULL REFERENCES orders(id), bill_id TEXT UNIQUE, payment_url TEXT, status TEXT NOT NULL CHECK(status IN ('creating','pending','paid','failed')), created_at INTEGER NOT NULL);
CREATE UNIQUE INDEX attempt_active ON payment_attempts(order_id) WHERE status IN ('creating','pending');
CREATE TABLE enrollments (user_id TEXT NOT NULL REFERENCES user(id) ON DELETE CASCADE, course_id TEXT NOT NULL REFERENCES courses(id) ON DELETE CASCADE, order_id TEXT REFERENCES orders(id), created_at INTEGER NOT NULL, PRIMARY KEY(user_id,course_id));
CREATE TABLE progress (user_id TEXT NOT NULL REFERENCES user(id) ON DELETE CASCADE, lesson_id TEXT NOT NULL REFERENCES lessons(id) ON DELETE CASCADE, position_seconds INTEGER NOT NULL CHECK(position_seconds >= 0), completed INTEGER NOT NULL DEFAULT 0 CHECK(completed IN (0,1)), updated_at INTEGER NOT NULL, PRIMARY KEY(user_id,lesson_id));
CREATE TABLE email_outbox (id TEXT PRIMARY KEY, order_id TEXT NOT NULL UNIQUE REFERENCES orders(id), recipient TEXT NOT NULL, sent_at INTEGER);
