ALTER TABLE courses ADD COLUMN category TEXT NOT NULL DEFAULT 'Umum';
ALTER TABLE courses ADD COLUMN archived INTEGER NOT NULL DEFAULT 0 CHECK(archived IN (0,1));
ALTER TABLE lessons ADD COLUMN resource_links TEXT NOT NULL DEFAULT '';
